Repository UlugbekAsadov/Electon-Frontend, pull requests merged in 2023-06, with the labels that each got.

#3 bugfix: console errors resolved
  app/layout.tsx
Labels: bug

#4 ELE-30: top header created
  app/page.tsx
  assets/icons/location.svg
  assets/icons/track.svg
  components/sections/index.ts
  components/sections/top-header-element.tsx
  tailwind.config.js
Labels: bug, feature

#5 ELE-31: create-login page
  app/globals.css
  app/login/page.tsx
  app/register/page.tsx
  assets/icons/loader.svg
  assets/image/Saly-14.png
  components/common/button.tsx
  components/common/index.ts
  components/common/input.tsx
  components/sections/auth-content.tsx
  components/sections/login-form.tsx
  components/sections/register-form.tsx
  package-lock.json
  package.json
  shared/enum/auth-types.enum.ts
  shared/enum/index.ts
  shared/interfaces/auth.interface.ts
  shared/interfaces/index.ts
  shared/utils/index.ts
  tailwind.config.js
Labels: feature
